<a href="https://colab.research.google.com/github/ronikapaul2000/Machine_Learning_Lab/blob/main/svd%2Cmatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print("type: %s" %type(a))            # Prints "<class 'numpy.ndarray'>"
print("shape: %s" %a.shape) 
print(a[0], a[1], a[2])  
a[0] = 5
print(a)     

type: <class 'numpy.ndarray'>
shape: 3
1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print("\n shape of b:",b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"


 shape of b: (2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print("All zeros matrix:\n  %s" %a)          

All zeros matrix:
  [[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print("\nAll ones matrix:\n  %s" %b)              


All ones matrix:
  [[1. 1.]]


In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print("\n identity matrix: \n%s"%d)   


 identity matrix: 
[[1. 0.]
 [0. 1.]]


In [ ]:

e = np.random.random((2,2))  # Create an array filled with random values
print("\n random matrix: \n%s"%e)


 random matrix: 
[[0.56445517 0.83640293]
 [0.08708479 0.06639031]]


In [ ]:
#vectorized sum
print("Vectorized sum example\n")
x = np.array([[1,2],[3,4]])
print("x:\n %s" %x)
print("sum: %s"%np.sum(x))  # Compute sum of all elements; prints "10"
print("sum axis = 0: %s" %np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print("sum axis = 1: %s" %np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"



Vectorized sum example

x:
 [[1 2]
 [3 4]]
sum: 10
sum axis = 0: [4 6]
sum axis = 1: [3 7]


In [ ]:
#matrix dot product
a = np.arange(10000)
b = np.arange(10000)

dp = np.dot(a,b)

print("Dot product: %s\n" %dp)

Dot product: 333283335000



In [ ]:
#outer product
op = np.outer(a,b)
print("\n Outer product: %s\n" %op)


 Outer product: [[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]



In [ ]:
#elementwise product

ep = np.multiply(a, b)

print("\n Element Wise product: %s \n" %ep)


 Element Wise product: [       0        1        4 ... 99940009 99960004 99980001] 



In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print("Original x: \n%s " %x)    # Prints "[[1 2]
            #          [3 4]]"
print("\nTranspose of x: \n%s" %x.T)  # Prints "[[1 3]
            #          [2 4]]"

Original x: 
[[1 2]
 [3 4]] 

Transpose of x: 
[[1 3]
 [2 4]]


In [ ]:
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("A: \n%s" %A)
# SVD
U, s, VT = svd(A)
print("\nU: \n%s" %U)
print("\ns: \n %s" %s)
print("\nV^T: \n %s" %VT)

A: 
[[1 2]
 [3 4]
 [5 6]]

U: 
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s: 
 [9.52551809 0.51430058]

V^T: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
